web:
  build: .
  command: 'bash -c ''target/universal/stage/bin/katangapp-backend -Dhttp.port=${PORT}'''
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user'
